version: '2'
services:
  okimochi:
    build: ./okimochi
    image: joemphilips/okimochi:latest
    env_file: .env
    command: node index.js
    volumes:
      - ".:/usr/app"
    ports:
      - "3000:3000"
    environment:
      PORT: 8080
    restart: always
    networks:
      okimochi-network:
        ipv4_address: 172.0.0.2
    tty: true
    stdin_open: true
  bitcoind:
    image: seegno/bitcoind:0.14.2-alpine
    volumes:
      - "./bitcoin:/home/bitcoin/.bitcoin"
    networks:
      okimochi-network:
        ipv4_address: 172.0.0.3
    ports:
      - "8332:8332"
      - "8333:8333"
      - "18332:18332"
      - "18333:18333"
      - "18444:18444"
    command:
      -printtoconsole
      -rest
      -testnet
      -server
      -rpcuser=slackbot
      -rpcpassword=bitcoin-tipper
      -rpcallowip=172.0.0.0/8
  mongo:
    restart: always
    image: mongo
    networks:
      okimochi-network:
        ipv4_address: 172.0.0.4
    command:
      --dbpath=/data/db
      --rest
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - "./userdb:/data/db"

networks:
  okimochi-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/16
          gateway: 172.0.0.1
