version: '2'
services:
  okimochi:
    build: ./okimochi
    image: joemphilips/okimochi:latest
    env_file: .env
    environment:
      NODE_ENV: development
    command: node index.js
    volumes:
      - ".:/usr/app"
    extra_hosts:
      - "mongo:172.0.0.4"
      - "bitcoind:172.0.0.3"
    restart: always
    ports:
      - "${HOST_PORT}:3000"
    networks:
      okimochi-network:
        ipv4_address: 172.0.0.2
    tty: true
    stdin_open: true
  bitcoind:
    image: seegno/bitcoind:0.14.2-alpine
    volumes:
      - "./bitcoin:/home/bitcoin/.bitcoin"
    networks:
      okimochi-network:
        ipv4_address: 172.0.0.3
    ports:
      - "8332:8332"
      - "8333:8333"
      - "18332:18332"
      - "18333:18333"
      - "18444:18444"
    command:
      -printtoconsole
      -rest
      -testnet
      -server
      -rpcuser=slackbot
      -rpcpassword=bitcoin-tipper
      -rpcallowip=172.0.0.0/8
      -datadir=/home/bitcoin/.bitcoin
  mongo:
    restart: always
    image: mongo
    networks:
      okimochi-network:
        ipv4_address: 172.0.0.4
    command:
      --dbpath=/data/db
      --rest
    volumes:
      - "./userdb:/data/db"

networks:
  okimochi-network:
    external: true
