version: '2'
services:
  okimochi:
    build: ./okimochi
    image: joemphilips/okimochi:latest
    env_file: .env
    command: node index.js
    networks:
      - okimochi
    volumes:
      - ".:/usr/app"
    ports:
      - "3000:3000"
    environment:
      PORT: 8080
    restart: always
    links:
      - mongo
      - bitcoind
    tty: true
    stdin_open: true
  bitcoind:
    image: seegno/bitcoind:0.14.2-alpine
    networks:
      - okimochi
    volumes:
      - "./bitcoin:/home/bitcoin/.bitcoin"
    ports:
      - "8332:8332"
      - "8333:8333"
      - "18332:18332"
      - "18333:18333"
      - "18444:18444"
    command:
      -printtoconsole
      -rest
      -testnet
      -server
      -rpcpassword=bitcoin-tipper
      -rpcuser=slackbot
      -rpcallowip=192.168.0.0/16
  mongo:
    networks:
      - okimochi
    restart: always
    image: mongo
    command:
      --dbpath=/data/db
      --rest
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - "./userdb:/data/db"

networks:
  okimochi:
    external: true
