version: 2
jobs:
  build:
    working_directory: /home/circleci/okimochi
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: install npm packages
          command: 'cd okimochi && npm install'
  test:
    steps:
      - checkout
      - run:
          name: test
          command: 'cd okimochi && npm test'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
          - build
