version: 2
jobs:
  build:
    working_directory: /home/circleci/okimochi
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: install npm packages
          command: 'cd okimochi && npm install'
      - run: 'cd okimochi && npm test'

      - setup_remote_docker

      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
          export PATH=/tmp/docker/:$PATH

      - run:
          name: build docker image for okimochi only.
          command: |
            "docker build okimochi -f okimochi/Dockerfile --no-cache --tag okimochi:temp"
      # deploy
      - run:
          name: register to ecr and deploy to ecs
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              ./.circleci/deploy-ecs.sh
            fi

