version: 2
jobs:
  build:
    working_directory: /home/circleci/okimochi/okimochi
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: 'npm install'
  test:
    working_directory: /home/circleci/okimochi/okimochi
    docker:
      - image: circleci/node:7.10
    steps:
      - run: 'npm test'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
