version: 2
jobs:
  build:
    working_directory: /home/circleci/okimochi
    docker:
      - image: joemphilips/node7-awscli-docker:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "okimochi/package.json" }}
      - run:
          name: install npm packages
          command: 'cd okimochi && npm install'
      - save_cache:
          key: dependency-cache-{{ checksum "okimochi/package.json" }}
          paths:
            - okimochi/.node_modules
      - run: 'cd okimochi && npm test'

      - setup_remote_docker

      - run:
          name: Run integration test by docker compose
          command: |
            NODE_ENV=test docker-compose run okimochi
      # deploy
      - run:
          name: register to ecr and deploy to ecs
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./.circleci/deploy-ecs.sh
            fi

