version: 2
jobs:
  build:
    working_directory: /home/circleci/okimochi
    docker:
      - image: joemphilips/node7-awscli
    steps:
      - checkout

      # build
      - type: cache-restore
        key: okimochi-{{ checksum "okimochi/package.json"}}
      - run:
          name: install npm packages
          command: 'cd okimochi && npm install'

      # test
      - run: 'cd okimochi && npm test'

      # deploy
      - run:
          name: register to ecr and deploy to ecs
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              ./.circleci/deploy-ecs.sh
            fi

